### ISSUE TITLE
In ProjLRP_Functions.r can I remove "coho" from the names of variables and data files?

### ISSUE THREAD

**Issue by carrieholt** [Pacific-salmon-assess/SalmonLRP_RetroEval#10]
These are all derived/saved within the species-specific directories, so it should be obvious what they are, and then the ProjLRP_Functions.R could be a bit more generic:

Variables:
cohoRecDataTrim

Data files:
cohoCorrMat.csv
cohoRickerSurv_mcmc.csv
cohoCUPars.csv (in both SamSimInputs and scenInputDir)
cohoSimPar.csv (in SamSimInputs)
cohoSimPars.csv (in scenInputDir) *

* and also wondering if there is a reason for having the two cohoSimPar / cohoSimPars files? I know they are different, but they are in different folders, so could be named the same?

**Comment by krHolt** [comment]
I have updated code in ProjLRP_Functions.r so that coho name is not used as a prefix when writing SamSimInput files to scenario directories.  I have also removed the coho prefix from cohoSimPars.csv (in SamSimInputs) and cohoCUPars.csv (in both SamSimInputs).  Note that as part of this, I re-named the former 'SamSimInputs/cohoSimPar.csv' to 'SamSimInputs/cohoSimPars.csv' [with an s], as suggested.

@carrieholt  - can you please confirm that this update works for you?

**Comment by carrieholt** [comment]
Yes, it works:)
