### ISSUE TITLE
Q: do projections for IFC draw from MCMC posteriors for SR parameters?

### ISSUE THREAD

**Issue by carrieholt** [Pacific-salmon-assess/SalmonLRP_RetroEval#11]
This is a question more than an issue. I thought that the projection was pulling from the MCMC posteriors of the SR model estimates, but I can't find the code for it. It looks like genericRecoverySim() uses the median of the posteriors in the projections. Correct? If that is the case,  I wonder if we may want to change that to align with projections in RPAs?

**Comment by krHolt** [comment]
Yes, they do.

The code to sample from the MCMC posterior in samSim-LRP branch is here:
Line 184 of genericRecoverySimulator.r:
# If .csv of par dist is passed, change from median values to sample from par dist
  if (is.null(ricPars) == FALSE) {
        dum <- getSRPars_randomSamp(pars = ricPars, stks = stkID) 
       .... }

A csv of the posterior gets passed to genericRecoverySim for the coho case study here:
Line 143 of ProjLRP_Functions.r:
genericRecoverySim(.... ricPars=mcmcOut....)

The above code is set-up so that if ricPars == NULL, then the medians get used.  So long as a csv is passed to ricPars, then the getSRPars_randomSamp() function is called to sample the posterior.

@carrieholt - Let me know if there is anything missing from this.

**Comment by carrieholt** [comment]
I see. Although I had downloaded the samSim LRP branch within the projection code, I had not pulled  the updates to my git folder on my desktop, so I was looking at an outdated genericRecoverySimulator() file. All good now.
