### ISSUE TITLE
Model diagnostic outputs in annualRetro_SRparsByCU.csv

### ISSUE THREAD

**Issue by lukewarkentin** [Pacific-salmon-assess/SalmonLRP_RetroEval#5]
@krHolt, question for you: the runAnnualRetro function creates annualRetro_SRparsByCU.csv outputs, which have columns titled "z.value" and "Pr...z.2..". I think these are for the model diagnostics, but (I think) because there are unique values for each parameter estimate for each model fit, it makes the annualRetro_SRparsByCU.csv have a lot of extra rows, which makes pulling out the estimated stock-recruit parameters for each fit difficult. Are the  "z.value" and "Pr...z.2.." columns necessary in the  annualRetro_SRparsByCU.csv file? If yes, then I will make my graphing code work with that structure. Thanks.

**Comment by krHolt** [comment]
No, these columns are not needed on the SRpars_ByCU.csv file.  They get automatically put into All_Ests because they are now being output from the tmb code so that we can use them to calculate logistic model diagnostics.  You can go ahead and exclude them from the SR parameter extractions in runAnnualRetro().  Looks like you could do this when you create RickerEsts or when you create outSR.df.

**Comment by lukewarkentin** [comment]
Fixed this issue.
